#------------LobbyX------------
#Project by XMC-Plugins
#Discord: https://discord.gg/7x2fzYKucZ
#------------LobbyX------------

#Prefix
Prefix: '&f[&b&lLobby&4&lX&f] &r'


#Settings
#Change the settings as they are perfect for you

Settings:
  MobDamageInLobbys: false
  DefaultWeather: CLEAR #Select between Clear, Rain, Thunder
  DefaultGamemode: SURVIVAL
  DailyRewardCoinsAmount: 2000
  DefaultRank: default #This rank MUST exist in the ranks.yml file!
  OperatorRank: mod #This rank MUST exist tn the ranks.yml file!

#LobbyWorlds

Lobby_Worlds: #All worlds where the lobby system is to be used
  world:
    maintenance: false
  lobby:
    maintenance: false

#Permissions
#Change the permission for commands and other thinks
Permissions:
  LobbyXCommandPermission: lobbyx.lobbyx
  BuildCommandPermission: lobbyx.build
  CreateNewLobbyWorld: lobbyx.world
  CoinsCommandPermission: lobbyx.coins
  MaintenanceModsPermission: lobbyx.maintenance

#Inventorys
#Change the inventory titles

Inventory:
  MainInventoryTitle: '&bLobby&4X&f - &6Main'
  ProfileInventoryTitle: '&bLobby&4X&f - &6Profile'
  SocialInventoryTitle: '&bLobby&4X&f - &9Social'
  FriendInventoryTitle: '&bLobby&4X&f - &3Friends'
  LocationInventoryTitle: '&bLobby&4X&f - &9Locations'
  LanguageInventoryTitle: '&bLobby&4X&f - &3Language'
  FriendSettingsInventoryTitle: '&bLobby&4X&f - &bFriend Settings'
  FriendRemoveInventoryTitle: '&bLobby&4X&f - &cRemove this Friend'
  LobbySelectorInventoryTitle: '&bLobby&4X&f - &dLobbys'
  WorldCreatorInventoryTitle: '&bLobby&4X&f - &2World Creator'
  TeleporterInventoryTitle: '&bLobby&4X&f - &5Navigator'
  InteractwithplayerInventory: '&bLobby&4X&f - &3PlayerInfo'
  Rank:
    RankInventory: '&bLobby&4X&f - &9Ranks'
    RankSettingsInventory:
      RankSettingsInventory: '&bLobby&4X&f - &bRank Settings'
      CreateRankInventory: '&bLobby&4X&f - &2Create Rank'
      RankPermissionInventory: '&bLobby&4X&f - &6Rank Permissions'
  ClanInventory:
    ClanChooseInventoryTitle: '&bLobby&4X&f - &4You arent in a Clan'
    ClanMemberInventoryTitle: '&bLobby&4X&f - &3Clan - Member'
    ClanLeaderInventoryTitle: '&bLobby&4X&f - &3Clan - Leader'
    ClanMember1InventoryTitle: '&bLobby&4X&f - &3Clan - &7Member'
  GadgetsInventory:
    GadgetsMainMenu: '&bLobby&4X&f - &3Gadgets Main Menu'
    HeadInventory: '&bLobby&4X&f - &eHeads'
    SpecialItemInventory: '&bLobby&4X&f - &9Special Items'
    AnimatedHeadsInventory: '&bLobby&4X&f - &6Animated Heads'

#Tablist
#Change tablist look

Tablist:
  #Use '~' to create paragraphs!
  Header: '&r ~ &bLobby&4X &8- &6Lobby ~ &aOnline: &6%SERVER_ONLINE%&8/&6%SERVER_MAX_PLAYERS% &8● &dServer: &b%PLAYER_SERVER% &8● &2Ping: &b%PLAYER_PING%ms ~'
  Footer: '&r~ &bTwitter &8» §f@????? &8&l| &9TeamSpeak &8» &f????? &8&l| &4Youtube: &8» &f?????'
  Update_Delay: 20 #in minecraft ticks bsp. 20 ticks = 1 sec          !!!Attention, the smaller the number, the more the server can lay!!

Broadcaster:
  enabled: true
  delay: 300 #delay in seconds
  messages:
    - '&fYou can change this messages in the &3config.yml&f file.'
    - '&fDo &6/lx &fto edit the navigator and more.'
    - '&fSet you language under &3Profile &f-> &cSettings &f-> &6Language&f!'
    - '&fDo &5/daily &fto claim you daily coins.'
    - '&fAdd &3Friends&f with &6/friend add <Player>'

#Items
#Customize the Lobby-Items

Items:
  Teleporter:
    enabled: true
    slot: 4
    material: COMPASS
    displayname: '&5Navigator &8| &7Right-Click'
  Gadgets:
    enabled: true
    slot: 0
    material: CHEST
    displayname: '&bGadgets &8| &7Right-Click'
  Profile:
    enabled: true
    slot: 1
    displayname: '&2Profile &8| &7Right-Click'
  Hider_ON:
    enabled: true
    slot: 7
    material: LIME_DYE
    displayname: '&7Player: &aShown &8| &7Right-Click'
  Hider_OFF:
    enabled: true
    slot: 7
    material: GRAY_DYE
    displayname: '&7Player: &cHidden &8| &7Right-Click'
  Selector:
    enabled: true
    slot: 8
    material: FIREWORK_STAR
    displayname: '&dLobby Selector &8| &7Right-Click'

#Titles
#Customize the Titles

Titles:
  WelcomeTitle:
    enabled: true
    title: '&aWelcome &6%PLAYER%'
    subtitle: '&7Have fun on &bYourServer.net'

#Scoreboad
#Customize the Scoreboard

Scoreboard:
  Title: '&b&lLobby&4&lX &f&l- &5Lobby'
  UpdateDelay: 20 #in ticks 20 ticks = 1 sec
  Lines:
    - "&8%DATE% - %TIME%"
    - "&1"
    - "&7Player ➔ &6%PLAYER%"
    - "&2"
    - "&7Clan ➔ &6%CLAN%"
    - "&7Coins ➔ &6%COINS%"
    - "&7Online Friends ➔ &6%ONLINE_FRIENDS%"
    - "&3"
    - "&7Rank ➔ %RANK%"
    - "&6"
    - "&aYourServer.net"

#JumpAndRun
#Customize the JumpAndRun

JumpAndRun:
  Sounds:
    StartSound: ENTITY_PLAYER_LEVELUP
    StopSound: ITEM_SHIELD_BREAK
    NewBlockSound: BLOCK_NOTE_BLOCK_PLING
  Actionbar:
    enabled: true
    ActionbarText: '&bYour points: &6%JUMP_AND_RUN_POINTS%'
  Blocks:
    NewBlock: WHITE_WOOL
    StandingBlock: WHITE_CONCRETE

LobbySelector:
  enabled: true
  Material: GHAST_TEAR
  Name: '&6Lobby &f&l- &b%WORLD_NAME%'

ChatFormat:
  ChatFormatRank: '&6[%RANK%&6] &3%PLAYER% &5>> &f%MESSAGE%'
  ChatFormatWithout: '&3%PLAYER% &5>> &f%MESSAGE%'