#------------LobbyX------------
#Project by XMC-Plugins
#Discord: https://discord.gg/7x2fzYKucZ
#------------LobbyX------------

#Prefix
Prefix: '&f[&b&lLobby&4&lX&f] &r'


#Settings
#Change the settings as they are perfect for you

Settings:


#LobbyWorlds

Lobby_Worlds: #All worlds where the lobby system is to be used
  - world
  - lobby

#Permissions
#Change the permission for commands and other thinks
Permissions:
  LobbyXCommandPermission: lobbyx.lobbyx
  BuildCommandPermission: lobbyx.build

#Inventorys
#Change the inventory titles

Inventory:
  MainInventoryTitle: '&bLobby&4X&f - &6Main'
  ProfileInventoryTitle: '&bLobby&4X&f - &6Profile'

#Tablist
#Change tablist look

Tablist:
  #Use '~' to create paragraphs!
  Header: '&r ~ &bLobby&4X &8- &6Lobby ~ &aOnline: &6%SERVER_ONLINE%&8/&6%SERVER_MAX_PLAYERS% &8● &dServer: &b%PLAYER_SERVER% ~'
  Footer: '&r~ &bTwitter &8» §f@????? &8&l| &9TeamSpeak &8» &f????? &8&l| &4Youtube: &8» &f?????'