#------------LobbyX------------
#Project by XMC-Plugins
#Discord: https://discord.gg/7x2fzYKucZ
#------------LobbyX------------

#Prefix
Prefix: '&f[&b&lLobby&4&lX&f] &r'


#Settings
#Change the settings as they are perfect for you

Settings:
  MobDamageInLobbys: false
  DefaultWeather: CLEAR #Select between Clear, Rain, Thunder
  DefaultGamemode: SURVIVAL

#LobbyWorlds

Lobby_Worlds: #All worlds where the lobby system is to be used
  - world
  - lobby

#Permissions
#Change the permission for commands and other thinks
Permissions:
  LobbyXCommandPermission: lobbyx.lobbyx
  BuildCommandPermission: lobbyx.build

#Inventorys
#Change the inventory titles
#
Inventory:
  MainInventoryTitle: '&bLobby&4X&f - &6Main'
  ProfileInventoryTitle: '&bLobby&4X&f - &6Profile'
  SocialInventoryTitle: '&bLobby&4X&f - &9Social'
  FriendInventoryTitle: '&bLobby&4X&f - &3Friends'
  LocationInventoryTitle: '&bLobby&4X&f - &9Locations'
  LanguageInventoryTitle: '&bLobby&4X&f - &3Language'
  FriendSettingsInventoryTitle: '&bLobby&4X&f - &bFriend Settings'
  FriendRemoveInventoryTitle: '&bLobby&4X&f - &cRemove this Friend'
  ClanInventory:
    ClanChooseInventoryTitle: '&bLobby&4X&f - &4You aren´t in a Clan&f - &aHere you can Join one'
  GadgetsInventory:
    GadgetsMainMenu: '&bLobby&4X&f - &bGadgets Main Menu'

#Tablist
#Change tablist look

Tablist:
  #Use '~' to create paragraphs!
  Header: '&r ~ &bLobby&4X &8- &6Lobby ~ &aOnline: &6%SERVER_ONLINE%&8/&6%SERVER_MAX_PLAYERS% &8● &dServer: &b%PLAYER_SERVER% &8● &2Ping: &b%PLAYER_PING%ms ~'
  Footer: '&r~ &bTwitter &8» §f@????? &8&l| &9TeamSpeak &8» &f????? &8&l| &4Youtube: &8» &f?????'
  Update_Delay: 20 #in minecraft ticks bsp. 20 ticks = 1 sec          !!!Attention, the smaller the number, the more the server can lie!!

#Items
#Customize the Lobby-Items

Items:
  Teleporter:
    enabled: true
    slot: 4
    material: COMPASS
    displayname: '&5Navigator &8| &7Right-Click'
  Gadgets:
    enabled: true
    slot: 0
    material: CHEST
    displayname: '&bGadgets &8| &7Right-Click'
  Profile:
    enabled: true
    slot: 1
    displayname: '&2Profile &8| &7Right-Click'
  Hider_ON:
    enabled: true
    slot: 7
    material: LIME_DYE
    displayname: '&7Player: &aShown &8| &7Right-Click'
  Hider_OFF:
    enabled: true
    slot: 7
    material: GRAY_DYE
    displayname: '&7Player: &cHidden &8| &7Right-Click'
  Selector:
    enabled: true
    slot: 8
    material: FIREWORK_STAR
    displayname: '&dLobby Selector &8| &7Right-Click'

#Titles
#Customize the Titles

Titles:
  WelcomeTitle:
    enabled: true
    title: '&aWelcome &6%PLAYER%'
    subtitle: '&7Have fun on &bYourServer.net'

#JumpAndRun
#Customize the JumpAndRun

JumpAndRun:
  Sounds:
    StartSound: ENTITY_PLAYER_LEVELUP
    StopSound: ITEM_SHIELD_BREAK
    NewBlockSound: BLOCK_NOTE_BLOCK_PLING
  Actionbar:
    enabled: true
    ActionbarText: '&bYour points: &6%JUMP_AND_RUN_POINTS%'
  Blocks:
    NewBlock: WHITE_WOOL
    StandingBlock: WHITE_CONCRETE