name: LobbyX
version: '${project.version}'
main: de.theredend2000.lobbyx.Main
api-version: 1.19
author: XMC-Plugins
depend: [ProtocolLib]
softdepend: [NoteBlockAPI]
commands:
  lobby:
    description: teleports you to the lobby
    aliases:
      - l
      - hub
  lobbyx:
    aliases:
      - lx
  build:
    aliases:
      - b
  friend:
    aliases:
      - fr
  jnr:
    aliases:
      - jumpandrun
  setLang:
    aliases:
      - setlanguage
  clan:
    aliases:
      - cl
  music: