name: LobbyX
version: 1.0
main: de.theredend2000.lobbyx.Main
api-version: 1.19
author: XMC-Plugins
softdepend:
  - NoteBlockAPI
depend:
  - PowerRanks
commands:
  lobby:
    description: teleports you to the lobby
    aliases:
      - l
      - hub
  lobbyx:
    aliases:
      - lx
  build:
    aliases:
      - b
      - edit
  friend:
    aliases:
      - fr
  jnr:
    aliases:
      - jumpandrun
  setLang:
    aliases:
      - setlanguage
      - language
  clan:
    aliases:
      - cl
  reward:
    aliases:
      - claim
      - claimreward
  coins:
    aliases:
      - money
      - bal
      - budget
  hologram:
  msg:
    description: send other players messages
    aliases:
      - tell
      - me
  gamemode:
    aliases:
      - gm
      - mode
      - gamem
    description: toggle the gamemode